<a href="https://colab.research.google.com/github/MohammadForoutan/sandbox/blob/master/Preparation%20-%205%20Minutes%20Pytorch%20Tensor%20Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pytorch
import Numpy and Pytorch

In [8]:
import torch
import numpy

how to create tensors.
1. from simple arrays
2. use **numpy** arrays

In [9]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [10]:
np_data = numpy.array(data)
print(np_data)
print("------------")
x_np = torch.from_numpy(np_data)
print(x_np)

[[1 2]
 [3 4]]
------------
tensor([[1, 2],
        [3, 4]])


create array like another data(tensor or array)

In [11]:
x_ones = torch.ones_like(x_data)
print(x_ones)
print("------------")
x_rand_float = torch.rand_like(x_data, dtype=torch.float)
print(x_rand_float)

tensor([[1, 1],
        [1, 1]])
------------
tensor([[0.1262, 0.9169],
        [0.9240, 0.3798]])


generate data(ones, zeros)

In [13]:
x_ones_1 = torch.ones((2,3,))
print(x_ones_1)
print("------------")
x_zeros_1 = torch.zeros((4,3,))
print(x_zeros_1)
print("------------")
x_rand_1 = torch.rand((2,3,))
print(x_rand_1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
------------
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
------------
tensor([[0.5632, 0.4880, 0.0698],
        [0.0137, 0.4499, 0.9689]])


# Working with tensor properties

In [19]:
my_rand_array = torch.rand((2,3))

print(my_rand_array)
print("------------")
print("shape of tenor")
print("shape: ",my_rand_array.shape)
print("------------")
print("data type of tensor (float32, int64)")
print("data type: ",my_rand_array.dtype)
print("------------")
print("tensor device of tensor (cpu or gpu)")
print("weather device is working on cpu or gpu: ", my_rand_array.is_cuda)
print("data device: ",my_rand_array.device)
print("------------")
print("check cuda is available or not")
print("cuda(gpu) availablity: ",torch.cuda.is_available())


tensor([[0.2862, 0.7825, 0.4402],
        [0.5579, 0.3134, 0.9940]])
------------
shape of tenor
shape:  torch.Size([2, 3])
------------
data type of tensor (float32, int64)
data type:  torch.float32
------------
tensor device of tensor (cpu or gpu)
weather device is working on cpu or gpu:  False
data device:  cpu
------------
check cuda is available or not
cuda(gpu) availablity:  False


# Working with ternsors data

access tensors cells

In [25]:
x_rand_2 = torch.rand((2,3,))
print(x_rand_2)
print("------------")
print("row 1: ",x_rand_2[0])
print("------------")
print("row 2: ",x_rand_2[1])
print("------------")
print("column 1: ",x_rand_2[:,0])
print("------------")
print("column 2: ",x_rand_2[:,1])
print("------------")
print("column 3: ",x_rand_2[:,2])
print("------------")
print("column 1 and 2: ",x_rand_2[:,:2])
print("------------")
print("column 2 and 3: ",x_rand_2[:,1:])
print("------------")
print("cell in row 1 and column 1: ",x_rand_2[0,0])
print("------------")
print("cell in row 1 and column 2: ",x_rand_2[0,1])
print("------------")
print("cell in row 1 and column 3: ",x_rand_2[0,2])
print("------------")
print("cell in row 2 and column 1: ",x_rand_2[1,0])
print("------------")
print("cell in row 2 and column 2: ",x_rand_2[1,1])
print("------------")
print("cell in row 2 and column 3: ",x_rand_2[1,2])

tensor([[0.1535, 0.6570, 0.4223],
        [0.2168, 0.0153, 0.7382]])
------------
row 1:  tensor([0.1535, 0.6570, 0.4223])
------------
row 2:  tensor([0.2168, 0.0153, 0.7382])
------------
column 1:  tensor([0.1535, 0.2168])
------------
column 2:  tensor([0.6570, 0.0153])
------------
column 3:  tensor([0.4223, 0.7382])
------------
column 1 and 2:  tensor([[0.1535, 0.6570],
        [0.2168, 0.0153]])
------------
column 2 and 3:  tensor([[0.6570, 0.4223],
        [0.0153, 0.7382]])
------------
cell in row 1 and column 1:  tensor(0.1535)
------------
cell in row 1 and column 2:  tensor(0.6570)
------------
cell in row 1 and column 3:  tensor(0.4223)
------------
cell in row 2 and column 1:  tensor(0.2168)
------------
cell in row 2 and column 2:  tensor(0.0153)
------------
cell in row 2 and column 3:  tensor(0.7382)


# Concat and Multiply with arrays

## How to Concat tensors in pytorch

In [30]:
x_ones_3 = torch.ones((3,2,))
print(x_ones_3)
print("------------")
x_zeros_3 = torch.zeros((3,2))
print(x_zeros_3)
print("------------")
dt0 = torch.cat([x_ones_3, x_zeros_3], dim=0)
print("dim=0")
print(dt0)
print("------------")
dt1 = torch.cat([x_ones_3, x_zeros_3], dim=1)
print("dim=1")
print(dt1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
------------
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
------------
dim=0
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
------------
dim=1
tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]])


## How to Multiplication tensors in pytorch

In [32]:
x_rand_1 = torch.rand((4,4))
x_rand_2 = torch.rand((4,4))


x_out_0 = x_rand_1 @ x_rand_2
print(x_out_0)
print("------------")
x_out_1 = x_rand_1.matmul(x_rand_2)
print(x_out_1)


tensor([[0.8768, 2.0641, 1.3298, 1.3863],
        [0.9570, 1.3747, 1.0787, 0.9692],
        [0.5723, 1.1873, 1.0840, 0.4753],
        [1.0593, 2.1977, 1.8406, 1.1328]])
------------
tensor([[0.8768, 2.0641, 1.3298, 1.3863],
        [0.9570, 1.3747, 1.0787, 0.9692],
        [0.5723, 1.1873, 1.0840, 0.4753],
        [1.0593, 2.1977, 1.8406, 1.1328]])
----------------------


## transpose a tensor

In [36]:
x_rand_3 = torch.rand((4,6))
x_rand_4 = torch.rand((4,6))


# transpose x_rand_4
x_out_0 = x_rand_3 @ x_rand_4.T
print(x_out_0)
print("------------")
x_out_1 = x_rand_3.matmul(x_rand_4.T)
print(x_out_1)

tensor([[1.8341, 1.3690, 2.0436, 2.0974],
        [1.8504, 1.4084, 2.0825, 1.6316],
        [1.2962, 1.5015, 1.4883, 1.5524],
        [1.8020, 1.9722, 2.2819, 2.3988]])
------------
tensor([[1.8341, 1.3690, 2.0436, 2.0974],
        [1.8504, 1.4084, 2.0825, 1.6316],
        [1.2962, 1.5015, 1.4883, 1.5524],
        [1.8020, 1.9722, 2.2819, 2.3988]])


## Multiply each tensor cell like python array

In [39]:
x_rand_3 = torch.rand((4,6))
x_rand_4 = torch.rand((4,6))

print("x_rand_3")
print(x_rand_3)
print("------------")
print("x_rand_4")
print(x_rand_4)
print("------------")
z_1 = x_rand_3 * x_rand_4;
print(z_1)
print("------------")
z_2 = x_rand_3.mul(x_rand_4)
print(z_2)
print("------------")
z_3 = torch.mul(x_rand_3, x_rand_4)
print(z_3)


x_rand_3
tensor([[0.5319, 0.0468, 0.4165, 0.6616, 0.8738, 0.0554],
        [0.8548, 0.2917, 0.8186, 0.4006, 0.9103, 0.2895],
        [0.7449, 0.6590, 0.4227, 0.2631, 0.3698, 0.6816],
        [0.2309, 0.2639, 0.7159, 0.9911, 0.2769, 0.9318]])
------------
x_rand_4
tensor([[0.9778, 0.3691, 0.1210, 0.1673, 0.1244, 0.2637],
        [0.4124, 0.1312, 0.3953, 0.9231, 0.2815, 0.8365],
        [0.5720, 0.0923, 0.7138, 0.8461, 0.6694, 0.1585],
        [0.6006, 0.5953, 0.4397, 0.4149, 0.1557, 0.5886]])
------------
tensor([[0.5201, 0.0173, 0.0504, 0.1107, 0.1087, 0.0146],
        [0.3525, 0.0383, 0.3236, 0.3698, 0.2562, 0.2422],
        [0.4261, 0.0608, 0.3017, 0.2226, 0.2476, 0.1080],
        [0.1387, 0.1571, 0.3148, 0.4112, 0.0431, 0.5484]])
------------
tensor([[0.5201, 0.0173, 0.0504, 0.1107, 0.1087, 0.0146],
        [0.3525, 0.0383, 0.3236, 0.3698, 0.2562, 0.2422],
        [0.4261, 0.0608, 0.3017, 0.2226, 0.2476, 0.1080],
        [0.1387, 0.1571, 0.3148, 0.4112, 0.0431, 0.5484]])
-----------

## Sum in Tensors

In [40]:
x_ones_2 = torch.ones((3,2,))
print(x_ones_2)
print("------------")
x_sum = x_ones_2.sum()
print(x_sum)
print("------------")
x_sum_item = x_sum.item()
print(x_sum_item)



tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
------------
tensor(6.)
------------
6.0
------------


## more methods
Direct(in place) update in torch, without assigin value to another variable

In [41]:
x_ones_4 = torch.ones((3,2))
x_ones_4.add_(5)
print(x_ones_4)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]])


# Work with Datasets