<a href="https://colab.research.google.com/github/MohammadForoutan/sandbox/blob/master/Preparation%20-%205%20Minutes%20Pytorch%20Tensor%20Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Test if PyTorch is installed correctly:**

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # Check if GPU is accessible


2.5.1+cu121
False


**Basic PyTorch Operations**
**Create Tensors:**

In [3]:
import torch

# Create a tensor
x = torch.tensor([1.0, 2.0, 3.0])
print(x)

# Create a random tensor
random_tensor = torch.rand(3, 3)
print(random_tensor)


tensor([1., 2., 3.])
tensor([[0.6358, 0.3887, 0.2487],
        [0.6523, 0.2064, 0.6447],
        [0.2172, 0.4201, 0.0874]])


In [4]:
# Addition
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = a + b
print(c)

# Matrix Multiplication
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])
result = torch.matmul(matrix1, matrix2)
print(result)


tensor([5, 7, 9])
tensor([[19, 22],
        [43, 50]])
